# Generated by Django 5.1 on 2024-09-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policia',
            options={'verbose_name': 'Agregar preso', 'verbose_name_plural': 'Agregar presos'},
        ),
        migrations.AlterModelOptions(
            name='presos',
            options={'verbose_name': 'Agregar preso', 'verbose_name_plural': 'Agregar presos'},
        ),
        migrations.AddField(
            model_name='presos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presos',
            name='apellido',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
