# Generated by Django 5.1 on 2024-09-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Agregar preso',
                'verbose_name_plural': 'Agregar presos',
            },
        ),
    ]
